<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Couldnt find any notes in all categories</name>
   <tag></tag>
   <elementGuidId>5d7143da-2f8d-4d6e-a9f4-2af03e4f82c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4.my-2.mb-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div[4]/div[2]/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>2e0472a8-971f-45ac-829d-b49ac664b94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>no-notes-message</value>
      <webElementGuid>1eea60a7-63ac-447a-bdde-dd286cbca829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-2 mb-4</value>
      <webElementGuid>c7bce0f8-e375-47be-b785-1f1e10c6656e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Couldn't find any notes in all categories</value>
      <webElementGuid>5424b67c-edbf-4da0-8f2f-ff2640c76f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row mt-3&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 text-secondary text-center&quot;]/h4[@class=&quot;my-2 mb-4&quot;]</value>
      <webElementGuid>e49214c1-1649-42a4-9ca3-fa76943f00f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[4]/div[2]/div/h4</value>
      <webElementGuid>a59e1723-26ca-42ac-ba9c-e08a000d04fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You have completed all notes'])[1]/following::h4[1]</value>
      <webElementGuid>a116922f-dfe2-4af4-9f6a-294531fb03dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('', '&quot;', 'dsdsdsd', '&quot;', '')])[1]/following::h4[1]</value>
      <webElementGuid>cf55591c-5a19-4f74-b1b7-24b8e77a10d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Testing Practice Website'])[1]/preceding::h4[1]</value>
      <webElementGuid>e281eb3f-a90a-4657-ab8a-d28c0bb471eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expand Testing'])[1]/preceding::h4[2]</value>
      <webElementGuid>98e301bb-2d6c-4f36-9a71-6017256398ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>d7736cad-9cfa-4d12-a57e-fa4e4b9b5fdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = concat(&quot;Couldn&quot; , &quot;'&quot; , &quot;t find any notes in all categories&quot;) or . = concat(&quot;Couldn&quot; , &quot;'&quot; , &quot;t find any notes in all categories&quot;))]</value>
      <webElementGuid>11f24ad5-0011-442a-bba4-5136678abbd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
