<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Logout_search-input</name>
   <tag></tag>
   <elementGuidId>dd5d2fc5-6e1b-4bec-aa02-dcd69198bcf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3fe675cd-0bf3-4016-962a-4b83a89a5f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>20ca7dad-9307-4dca-8ffe-06302735252f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a6a8cd9b-0642-4f02-8b13-d7bc7dd870d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>search-input</value>
      <webElementGuid>ee45bf54-2f31-49a8-88cf-bac3eb75bae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search-input</value>
      <webElementGuid>bf1eb3be-46e9-40c0-af5d-690beca5d256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search notes...</value>
      <webElementGuid>4c46564a-600b-4380-a77f-420ff34d6655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-input&quot;)</value>
      <webElementGuid>5dc48967-e73e-4494-a558-71e9a6929b2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search-input']</value>
      <webElementGuid>dde17838-cdeb-4ca8-9c3b-1632130942c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-bar']/input</value>
      <webElementGuid>d4fbfd1d-5a16-4fc6-8ba3-57ce1f3cb857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>dc759375-9a3a-41f8-85ee-b2630e3b9c6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'search-input' and @placeholder = 'Search notes...']</value>
      <webElementGuid>b6574ccf-6656-44a6-b6d5-701d251705a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
