<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Personal</name>
   <tag></tag>
   <elementGuidId>6ed4ea02-d7b5-446a-b6ae-7dfeb028c4fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div[2]/div/div/button[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btnx-success.text-black.fw-bold.rounded.w-25.me-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e95397aa-ff23-4aea-bfd0-12dbaf57dfb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>category-personal</value>
      <webElementGuid>7bfac379-4af1-40e8-bb78-966b19bcdde7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btnx-success text-black fw-bold rounded w-25 me-3</value>
      <webElementGuid>85a840f0-65d6-4449-9164-ef3564320304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Personal•</value>
      <webElementGuid>99f66fc3-6cd3-4fbc-a3c2-d1de0f0fb0b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row mt-3&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-12 col-lg-8&quot;]/div[@class=&quot;d-flex&quot;]/button[@class=&quot;btn btnx-success text-black fw-bold rounded w-25 me-3&quot;]</value>
      <webElementGuid>5cfedf5a-c942-4352-95dd-12ef6f2a0f64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[2]/div/div/button[4]</value>
      <webElementGuid>a145aa80-dd3a-4158-85c8-2db5d2d5cbaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work'])[1]/following::button[1]</value>
      <webElementGuid>8398e137-30a8-4811-bee7-6e27d86ec537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='•'])[1]/following::button[2]</value>
      <webElementGuid>eae14a04-9040-4132-be40-2779cb64fcf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>3b4aacaf-829b-4941-8c69-ecd6063a195a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Personal•' or . = 'Personal•')]</value>
      <webElementGuid>3bf1fec8-5aca-4c27-be9d-ad473e295621</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
