<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Work</name>
   <tag></tag>
   <elementGuidId>2d0d75df-6125-470d-96e2-239810fd8c5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div[2]/div/div/button[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btnx-info.text-black.fw-bold.rounded.w-25.me-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>052b47d9-dd03-4ed6-ba05-300d1bca6cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>category-work</value>
      <webElementGuid>92fe46ca-4c21-4230-ae33-caf909469388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btnx-info text-black fw-bold rounded w-25 me-3</value>
      <webElementGuid>e883e80e-5ead-4c73-b3f5-00798743a089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Work•</value>
      <webElementGuid>4f1a746d-a2b3-41aa-b316-bd292c1050d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row mt-3&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-12 col-lg-8&quot;]/div[@class=&quot;d-flex&quot;]/button[@class=&quot;btn btnx-info text-black fw-bold rounded w-25 me-3&quot;]</value>
      <webElementGuid>21cd41b7-e0ca-4309-8a11-abd2d84ab958</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[2]/div/div/button[3]</value>
      <webElementGuid>98449ebe-9bae-46f5-b04c-b5e1c3a46f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='•'])[1]/following::button[1]</value>
      <webElementGuid>cb35998f-190e-4596-8ec0-4142c8623653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::button[1]</value>
      <webElementGuid>4fbdbdda-547a-496f-89c9-15b6a7086fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>0a3e24bf-a5b0-4746-9d03-cb57b141637d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Work•' or . = 'Work•')]</value>
      <webElementGuid>694aaa35-1741-4b42-b387-727bd6bd15e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
